version: '3.8'

services:
  modz-kiosk:
    build: .
    container_name: modz-kiosk
    ports:
      - "80:80"
    restart: unless-stopped
    healthcheck:
      disable: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.modz-kiosk.rule=Host(`kiosk.ridemodz.com`)"
      - "traefik.http.routers.modz-kiosk.entrypoints=https"
      - "traefik.http.routers.modz-kiosk.tls.certresolver=letsencrypt"
      - "traefik.http.services.modz-kiosk.loadbalancer.server.port=80"

